### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by Steeve55** [hash-bang/lodash-keyarrange#3]
It would be good please to update this library to be able to use it with typescript and also to be able to import it more easily.

Currently : 
![image](https://github.com/hash-bang/lodash-keyarrange/assets/54711522/5a1af97c-236f-451a-af3b-72eab1f96bcb)

Expected : 
![image](https://github.com/hash-bang/lodash-keyarrange/assets/54711522/fbdb7eeb-597e-45ea-92d9-95d30795d4f0)

Thank you.

**Comment by hash-bang** [comment]
Sorry @Steeve55 but I don't really work with Typescript.

I'm happy to accept a PR though if you wanted to write up its definitions?

**Comment by Steeve55** [comment]
Ok, no problem. I am sorry but I don't have time.
